### ISSUE TITLE
UOSL: problem with loading RData in step 01_T2_5_selection_criteria_from_PERSON_to_study_population.R

### ISSUE THREAD

**Issue by LAMaglan** [IMI-ConcePTION/DP2_SSRI-SNRI#10]
@OlgaPaoletti 
There is an error when running `01_T2_5_selection_criteria_from_PERSON_to_study_population.R` (see screenshot)
![DP2_01_T2_5_selection_criteria_error](https://github.com/IMI-ConcePTION/DP2_SSRI-SNRI/assets/29206211/b5286899-2f96-4b11-be3b-a857e21f29a0)

If I understand correctly, it tries to load "D3_mother_child_ids.RData",
![Screenshot from 2023-06-15 11-10-03](https://github.com/IMI-ConcePTION/DP2_SSRI-SNRI/assets/29206211/aaac3991-df05-46fe-9225-c2d7df54ebd5)

 but that is not something that is created
in the ARS-pregnancy algorithm (see screenshot of our output from v 4.1)
![Screenshot from 2023-06-15 11-08-21](https://github.com/IMI-ConcePTION/DP2_SSRI-SNRI/assets/29206211/d2bf8754-4986-4c64-80d9-81812757aa13)

**Comment by OlgaPaoletti** [comment]
This file is produced by the pregnancy algorithm v4.1. You should find it in the g_output folder. I will ask @GiorgioLimoncella

**Comment by LAMaglan** [comment]
Ok
@GiorgioLimoncella we are now (at UOSL) also running the pregnancy algorithm v4.2 (if relevant)

**Comment by OlgaPaoletti** [comment]
@LAMaglan Do you have the table PERSON_RELATIONSHIPS in your original istance?
In your ETL document I see the table

**Comment by LAMaglan** [comment]
@OlgaPaoletti  yes, see the screenshot for all the CDM tables we have (including PERSON_RELATIONSHIPS)
![UOSL_data](https://github.com/IMI-ConcePTION/DP2_SSRI-SNRI/assets/29206211/601c0305-e8e4-4cc0-affb-947c68f1fae6)

If relevant, we ran the newer pregnancy algorithm (v4.2), but there is also no "D3_mother_child_ids.RData".

**Comment by OlgaPaoletti** [comment]
I spoke with @GiorgioLimoncella and we have to modify a parameter in the pregnancy algorithm.  Monday we will provide you with the new pregnancy algorithm script, that will produce the D3_mother_child_ids that is missing now. So please wait for it before going ahead with the DP2 script

**Comment by LAMaglan** [comment]
@OlgaPaoletti @GiorgioLimoncella 
I have run the new ARS-pregnancy algorithm (v4.2.1), but cannot see any "D3_mother_child_ids.RData" in "g_output/".
Which point in the scripts is it made? Is it perhaps in another folder? No errors are provided - at least, the script continues to run all steps.

**Comment by LAMaglan** [comment]
@OlgaPaoletti @GiorgioLimoncella 
Have posted an issue in the ARS-pregnancy algorithm repo with some more details.
https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/issues/62
