### ISSUE TITLE
THL error for line launch_step("/p_steps/03_T2_2_create_components_pregnancy.R")

### ISSUE THREAD

**Issue by visama** [IMI-ConcePTION/DP2_SSRI-SNRI#11]
I get error for line launch_step("/p_steps/03_T2_2_create_components_pregnancy.R")

[1] "Detecting components for algorithm M1"
Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,  : 
  Incompatible join types: x.person_id (integer) and i.person_id (character)
Timing stopped at: 445.8 24.09 1206

I think the problem could be on line 155. Could fix person_id linkage types?
> sapply(get(paste0("selected_dispensing_",dr,"_pregnancy")), class)
            person_id                  date                codvar       indication_code prescriber_speciality 
          "character"                "Date"           "character"             "integer"           "character" 
> sapply(get(paste0("D4_study_population_",dr,"_pregnancy")), class)
   person_id pregnancy_id 
   "integer"  "character" 

@OlgaPaoletti

**Comment by OlgaPaoletti** [comment]
Thanks for the report (even if it is DP1). Can you please open step 02_T3_2_create_study_population_pregnancy and go in line 61:
  smart_load("D3_selection_criteria_from_PERSONS_to_study_population_pregnancy", dirtemp, extension = extension)
and substitute with: 
  smart_load("D3_selection_criteria_from_PERSONS_to_study_population_pregnancy", dirtemp, extension = "rds")

Save the step and try to rerun from line 91 (from launch_step("p_steps/02_T3_2_create_study_population_pregnancy.R") to 98 

Is the error still present?

**Comment by OlgaPaoletti** [comment]
Dear Visa, I still have a doubt about the subpopulations restricting meanings Davide used in the createspells in DP3
Do you have time to quickly check this in the next days?

**Comment by visama** [comment]
Thanks, it works now. Now in the same script I get an error:

[1] "Computing component I for EPILEPSY"
[1] "Computing component I for GAD"
[1] "Computing component I for NEUROPATHIC_PAIN"
[1] "Detecting components for algorithm S1"
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/home/vmaq/Kehitys/DP1_v2.1/g_intermediate/concept_sets/POTENTIAL_MISE_ABUSE.RData', probable reason 'No such file or directory'
Timing stopped at: 628.3 14.61 190.1

There is a file POTENTIAL_MISE_ABUSE_S1.RData in concept_sets-folder, but not just POTENTIAL_MISE_ABUSE.RData

**Comment by visama** [comment]
Yes, sure I can check subpopulations restricting meanings tomorrow or later this week. What exactly I should check?

**Comment by OlgaPaoletti** [comment]
I would like to meet you and try to run the createspells with the restriction in meanings (I remember some time ago we tried but we had some issues). If you have time we can try tomorrow
In the meatime I will correct the codelist for the POTENTIAL_MISE_ABUSE issue

**Comment by visama** [comment]
Yes, we can meet tomorrow. Im free 12-16 CET.

**Comment by OlgaPaoletti** [comment]
Perfect. We can do at 14 CET (15 in Finland)
